-- Oracle schema for warehouse order processing
-- Uses quoted identifiers to match EF Core Oracle provider naming.

-- Re-runnable cleanup section (safe for SQL Developer script execution)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "PickingTaskLines" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "PickingTasks" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "StockReservations" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "OrderLines" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "WarehouseOrders" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "StockBalances" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Items" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Warehouses" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "Customers" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "AuditLogs" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE "Customers" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR2(50) NOT NULL,
    "Name" VARCHAR2(250) NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "UQ_Customers_Code" UNIQUE ("Code")
);

CREATE TABLE "Warehouses" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" VARCHAR2(50) NOT NULL,
    "Name" VARCHAR2(250) NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "UQ_Warehouses_Code" UNIQUE ("Code")
);

CREATE TABLE "Items" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Sku" VARCHAR2(80) NOT NULL,
    "Name" VARCHAR2(250) NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "UQ_Items_Sku" UNIQUE ("Sku")
);

CREATE TABLE "StockBalances" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemId" NUMBER NOT NULL,
    "WarehouseId" NUMBER NOT NULL,
    "AvailableQuantity" NUMBER(18,3) DEFAULT 0 NOT NULL,
    "ReservedQuantity" NUMBER(18,3) DEFAULT 0 NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "FK_Stock_Item" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id"),
    CONSTRAINT "FK_Stock_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id"),
    CONSTRAINT "UQ_Stock_Item_Warehouse" UNIQUE ("ItemId", "WarehouseId"),
    CONSTRAINT "CK_Stock_Non_Negative" CHECK ("AvailableQuantity" >= 0 AND "ReservedQuantity" >= 0)
);

CREATE TABLE "WarehouseOrders" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderNumber" VARCHAR2(80) NOT NULL,
    "CustomerId" NUMBER NOT NULL,
    "WarehouseId" NUMBER NOT NULL,
    "Status" VARCHAR2(40) NOT NULL,
    "PickingStartedAt" TIMESTAMP(6),
    "ShippedAt" TIMESTAMP(6),
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "FK_Orders_Customer" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id"),
    CONSTRAINT "FK_Orders_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id"),
    CONSTRAINT "UQ_Orders_Number" UNIQUE ("OrderNumber")
);

CREATE TABLE "OrderLines" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" NUMBER NOT NULL,
    "ItemId" NUMBER NOT NULL,
    "Quantity" NUMBER(18,3) NOT NULL,
    "ReservedQuantity" NUMBER(18,3) DEFAULT 0 NOT NULL,
    "PickedQuantity" NUMBER(18,3) DEFAULT 0 NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "FK_OrderLines_Order" FOREIGN KEY ("OrderId") REFERENCES "WarehouseOrders"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderLines_Item" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id")
);

CREATE TABLE "StockReservations" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderLineId" NUMBER NOT NULL,
    "WarehouseId" NUMBER NOT NULL,
    "ItemId" NUMBER NOT NULL,
    "Quantity" NUMBER(18,3) NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "FK_Reservations_OrderLine" FOREIGN KEY ("OrderLineId") REFERENCES "OrderLines"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reservations_Warehouse" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id"),
    CONSTRAINT "FK_Reservations_Item" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id")
);

CREATE TABLE "PickingTasks" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TaskNumber" VARCHAR2(80) NOT NULL,
    "Status" VARCHAR2(40) NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "UQ_PickingTask_Number" UNIQUE ("TaskNumber")
);

CREATE TABLE "PickingTaskLines" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PickingTaskId" NUMBER NOT NULL,
    "OrderLineId" NUMBER NOT NULL,
    "Quantity" NUMBER(18,3) NOT NULL,
    "PickedQuantity" NUMBER(18,3) DEFAULT 0 NOT NULL,
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "FK_PickLines_Task" FOREIGN KEY ("PickingTaskId") REFERENCES "PickingTasks"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PickLines_OrderLine" FOREIGN KEY ("OrderLineId") REFERENCES "OrderLines"("Id")
);

CREATE TABLE "AuditLogs" (
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityName" VARCHAR2(120) NOT NULL,
    "EntityId" NUMBER NOT NULL,
    "Action" VARCHAR2(80) NOT NULL,
    "Details" VARCHAR2(2000),
    "CreatedAt" TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    "UpdatedAt" TIMESTAMP(6),
    "Version" NUMBER DEFAULT 0 NOT NULL
);

-- Performance indexes
CREATE INDEX "IX_Orders_Warehouse_Status_Created" ON "WarehouseOrders" ("WarehouseId", "Status", "CreatedAt");
CREATE INDEX "IX_Orders_Customer_Created" ON "WarehouseOrders" ("CustomerId", "CreatedAt");
CREATE INDEX "IX_OrderLines_OrderId" ON "OrderLines" ("OrderId");
CREATE INDEX "IX_OrderLines_ItemId" ON "OrderLines" ("ItemId");
-- UQ_Stock_Item_Warehouse already creates an index for ("ItemId", "WarehouseId")
CREATE INDEX "IX_StockReservations_OrderLineId" ON "StockReservations" ("OrderLineId");
CREATE INDEX "IX_PickingTasks_Status_Created" ON "PickingTasks" ("Status", "CreatedAt");
CREATE INDEX "IX_PickingTaskLines_TaskId" ON "PickingTaskLines" ("PickingTaskId");
CREATE INDEX "IX_Audit_Entity" ON "AuditLogs" ("EntityName", "EntityId", "CreatedAt");

-- Query-plan review statements
EXPLAIN PLAN FOR
SELECT "Id", "OrderNumber", "CustomerId", "WarehouseId", "Status", "CreatedAt"
FROM "WarehouseOrders"
WHERE "WarehouseId" = 1
  AND "Status" = 'Reserved'
  AND "CreatedAt" >= SYSTIMESTAMP - NUMTODSINTERVAL(30, 'DAY')
ORDER BY "CreatedAt" DESC;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR
SELECT sb."Id", sb."ItemId", sb."WarehouseId", sb."AvailableQuantity", sb."ReservedQuantity"
FROM "StockBalances" sb
WHERE sb."ItemId" = 1
  AND sb."WarehouseId" = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
