-- Oracle schema for warehouse order processing

CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL,
    name VARCHAR2(250) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT uq_customers_code UNIQUE (code)
);

CREATE TABLE warehouses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL,
    name VARCHAR2(250) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT uq_warehouses_code UNIQUE (code)
);

CREATE TABLE items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(80) NOT NULL,
    name VARCHAR2(250) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT uq_items_sku UNIQUE (sku)
);

CREATE TABLE stock_balances (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    available_quantity NUMBER(18,3) DEFAULT 0 NOT NULL,
    reserved_quantity NUMBER(18,3) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_stock_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_stock_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT uq_stock_item_warehouse UNIQUE (item_id, warehouse_id),
    CONSTRAINT ck_stock_non_negative CHECK (available_quantity >= 0 AND reserved_quantity >= 0)
);

CREATE TABLE warehouse_orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(80) NOT NULL,
    customer_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    status VARCHAR2(40) NOT NULL,
    picking_started_at TIMESTAMP(6),
    shipped_at TIMESTAMP(6),
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_orders_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT uq_orders_number UNIQUE (order_number)
);

CREATE TABLE order_lines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER(18,3) NOT NULL,
    reserved_quantity NUMBER(18,3) DEFAULT 0 NOT NULL,
    picked_quantity NUMBER(18,3) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES warehouse_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_lines_item FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE stock_reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id NUMBER NOT NULL,
    warehouse_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER(18,3) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_reservations_order_line FOREIGN KEY (order_line_id) REFERENCES order_lines(id) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_reservations_item FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE picking_tasks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number VARCHAR2(80) NOT NULL,
    status VARCHAR2(40) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT uq_picking_task_number UNIQUE (task_number)
);

CREATE TABLE picking_task_lines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    picking_task_id NUMBER NOT NULL,
    order_line_id NUMBER NOT NULL,
    quantity NUMBER(18,3) NOT NULL,
    picked_quantity NUMBER(18,3) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_pick_lines_task FOREIGN KEY (picking_task_id) REFERENCES picking_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_pick_lines_order_line FOREIGN KEY (order_line_id) REFERENCES order_lines(id)
);

CREATE TABLE audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR2(120) NOT NULL,
    entity_id NUMBER NOT NULL,
    action VARCHAR2(80) NOT NULL,
    details VARCHAR2(2000),
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6),
    version NUMBER DEFAULT 0 NOT NULL
);

-- Performance indexes
CREATE INDEX ix_orders_warehouse_status_created ON warehouse_orders (warehouse_id, status, created_at);
CREATE INDEX ix_orders_customer_created ON warehouse_orders (customer_id, created_at);
CREATE INDEX ix_order_lines_order_id ON order_lines (order_id);
CREATE INDEX ix_order_lines_item_id ON order_lines (item_id);
CREATE INDEX ix_stock_item_warehouse ON stock_balances (item_id, warehouse_id);
CREATE INDEX ix_stock_reservations_order_line ON stock_reservations (order_line_id);
CREATE INDEX ix_picking_tasks_status_created ON picking_tasks (status, created_at);
CREATE INDEX ix_picking_task_lines_task_id ON picking_task_lines (picking_task_id);
CREATE INDEX ix_audit_entity ON audit_logs (entity_name, entity_id, created_at);

-- Query-plan review statements
EXPLAIN PLAN FOR
SELECT id, order_number, customer_id, warehouse_id, status, created_at
FROM warehouse_orders
WHERE warehouse_id = :warehouse_id
  AND status = :status
  AND created_at >= :from_utc
ORDER BY created_at DESC;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR
SELECT sb.id, sb.item_id, sb.warehouse_id, sb.available_quantity, sb.reserved_quantity
FROM stock_balances sb
WHERE sb.item_id = :item_id
  AND sb.warehouse_id = :warehouse_id;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
